services:
  warehouse-a:
    environment:
      SCENARIO_DATA_PATH: /app/scenarios/competing-newer-states/warehouse-a.json

  warehouse-b:
    environment:
      SCENARIO_DATA_PATH: /app/scenarios/competing-newer-states/warehouse-b.json

  warehouse-c:
    environment:
      SCENARIO_DATA_PATH: /app/scenarios/competing-newer-states/warehouse-c.json
