x-warehouse-service: &warehouse-service
  image: lec-inventory-reconciliation-agent-warehouse:local
  build:
    context: .
    dockerfile: Dockerfile

services:
  warehouse-a:
    <<: *warehouse-service
    env_file:
      - config/warehouse-a.env
    ports:
      - "8001:8000"

  warehouse-b:
    <<: *warehouse-service
    env_file:
      - config/warehouse-b.env
    ports:
      - "8002:8000"

  warehouse-c:
    <<: *warehouse-service
    env_file:
      - config/warehouse-c.env
    ports:
      - "8003:8000"
